[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./scholarship-system"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100

[env]
# PORT will be set automatically by Railway
